import os
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from sqlalchemy import create_engine, text
from typing import List, Dict, Any
from core.optuna_tuner import QuantHyperTuner
import joblib
import json
import mlflow
import lightgbm as lgb
from airflow.exceptions import AirflowSkipException
from targets.target_engineer import TargetEngineer
from core.model_exporter import ProductionExporter
from features.feature_engineering import TechnicalFeatureEngineer
from features.feature_selector import QuantFeatureSelector

DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    try:
        from airflow.configuration import conf
        DATABASE_URL = conf.get('database', 'sql_alchemy_conn')
    except ImportError:
        pass

if DATABASE_URL and DATABASE_URL.startswith("postgresql://"):
    DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+psycopg2://")


def extract_full_history(logical_date_str: str) -> str:
    """
    Extracts a massive historical window (4 years + temporal buffer) from PostgreSQL, 
    computes all technical indicators via TechnicalFeatureEngineer, and rigorously 
    filters the dataset to ensure exactly 4 years of clean, NaN-free cross-sectional data 
    for the Walk-Forward Optimization.

    Args:
        logical_date_str (str): The logical execution date of the DAG (YYYY-MM-DD).

    Returns:
        str: Absolute file path to the engineered Parquet dataset.
    """
    engine = create_engine(DATABASE_URL)
    target_date = datetime.strptime(logical_date_str, "%Y-%m-%d").date()
    
    # 4 years (1460 days) + 300 days buffer for long-term indicators (e.g., 200 SMA)
    # Total extraction window: 1760 calendar days
    query = text("""
        SELECT * FROM market_data 
        WHERE date >= :target_date - interval '1760 days' AND date <= :target_date
    """)
    
    raw_df = pd.read_sql(query, engine, params={"target_date": target_date})
    
    if raw_df.empty:
        raise ValueError(f"FATAL: Database returned an empty dataframe for the window ending in {target_date}.")
        
    vix_df = raw_df[raw_df['ticker'] == 'VIX'].copy().set_index('date')
    assets_df = raw_df[raw_df['ticker'] != 'VIX'].copy().set_index('date')
    assets_df['ticker'] = assets_df['ticker'].astype('category')
    
    if vix_df.empty:
        raise ValueError("FATAL: VIX benchmark data is missing. Cannot calculate volatility returns.")
        
    vix_df['vix_return'] = np.log(vix_df['close'] / vix_df['close'].shift(1))
    
    # Merge VIX return explicitly.
    panel_df = assets_df.merge(vix_df[['vix_return']], left_index=True, right_index=True, how='left')
    
    if panel_df['vix_return'].isnull().all():
        raise ValueError("FATAL: vix_return merge failed. All values are NaN across the panel.")

    # --- FEATURE ENGINEERING ---
    # is_inference=False drops NaNs strictly (purging the 300-day buffer inherently)
    engineer = TechnicalFeatureEngineer()
    processed_df = engineer.transform(panel_df, is_inference=False)
    
    if processed_df.empty:
        raise ValueError("FATAL: Feature Engineering obliterated the dataset. Check target generation logic.")

    # --- STRICT TEMPORAL TRUNCATION ---
    # Enforce exactly 4 years of history (1460 days) to prevent Look-Ahead or unequal WFO blocks
    four_years_ago = pd.Timestamp(target_date - timedelta(days=1460))
    processed_df = processed_df[processed_df.index >= four_years_ago].copy()
    
    if len(processed_df) < 2000: # Sanity check for minimum density across 10+ ETFs
        raise ValueError(f"FATAL: Insufficient data density post-truncation. Only {len(processed_df)} rows survived.")

    print(f"Extraction successful. Evaluated columns: {processed_df.columns.tolist()}")
    print(f"Final WFO Dataset Shape: {processed_df.shape}")
    print(f"Dataset bounds: {processed_df.index.min()} to {processed_df.index.max()}")

    # --- TEMPORAL PERSISTENCE ---
    temp_dir = "/tmp/quant_engine_temp"
    os.makedirs(temp_dir, exist_ok=True)
    file_path = os.path.join(temp_dir, "heavy_train_data.parquet")
    
    processed_df.reset_index(inplace=True)
    processed_df.to_parquet(file_path, index=False)
    
    return file_path


def run_optuna_search(data_path: str) -> Dict[str, Any]:
    """
    Loads the historical WFO dataset, strictly isolates the final 40 active trading days 
    (reserving them exclusively for the blind Arena Duel), and executes Bayesian 
    Hyperparameter Optimization via Optuna over the remaining history.

    Args:
        data_path (str): Path to the Parquet dataset generated by the extraction task.

    Returns:
        Dict[str, Any]: The optimal hyperparameters discovered by Optuna to be passed via XCom.
    """
    if not os.path.exists(data_path):
        raise FileNotFoundError(f"FATAL: Historical dataset missing at {data_path}")

    df = pd.read_parquet(data_path)
    if df.empty:
        raise ValueError("FATAL: Optuna received an empty dataset.")

    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values('date')

    unique_dates = df['date'].unique()
    if len(unique_dates) < 500: 
        raise ValueError(f"FATAL: Insufficient history. Only {len(unique_dates)} days available.")

    cutoff_date = unique_dates[-40]
    optuna_df = df[df['date'] < cutoff_date].copy()

    backtester_args = {
        'train_days': 252, 
        'step_days': 20,   
        'embargo_days': 5,
        'n_features': 15 
    }

    search_space = {
        "q_high": (0.60, 0.75),
        "q_low": (0.25, 0.40),
        "buy_threshold": (0.40, 0.60),
        "sell_threshold": (0.40, 0.60),
        "weight_buy": (1.0, 1.5),
        "weight_sell": (1.5, 2.5),
        "weight_neutral": (0.8, 2.0),
        "n_estimators": (70, 200),
        "max_depth": (3, 7),
        "num_leaves": (10, 50),
        "learning_rate": (0.01, 0.1),
        "min_child_samples": (50, 300),
        "reg_alpha": (1e-3, 10.0),
        "reg_lambda": (1e-3, 10.0)
    }

    try:
        tuner = QuantHyperTuner(panel_df=optuna_df, backtester_args=backtester_args, search_space=search_space)
        best_params = tuner.optimize(n_trials=40, seed=1)
    except Exception as e:
        raise RuntimeError(f"FATAL: Optuna optimization crashed. Details: {str(e)}")

    if not best_params:
        raise ValueError("FATAL: Optuna returned empty parameters.")
    
    return best_params

def select_top_features(data_path: str) -> List[str]:
    """
    Evaluates the entire historical training window to lock in the top 15 features 
    that will be hardcoded into the production JSON manifest.
    """
    if not os.path.exists(data_path):
        raise FileNotFoundError(f"FATAL: Historical dataset missing at {data_path}")

    df = pd.read_parquet(data_path)
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values('date')

    unique_dates = df['date'].unique()
    cutoff_date = unique_dates[-40]
    train_df = df[df['date'] < cutoff_date].copy()

    target_maker = TargetEngineer(q_high=0.66, q_low=0.33)
    train_df = target_maker.fit_transform(train_df)
    
    drop_cols = ['target', 'fwd_log_return', 'close', 'ticker', 'date']
    X_train = train_df.drop(columns=drop_cols, errors='ignore')
    y_train = train_df['target']

    selector = QuantFeatureSelector(n_features=15)
    top_features = selector.select(X_train, y_train)
    
    print(f"Top 15 features selected for production: {top_features}")
    return top_features


def promote_heavy_challenger(data_path: str, selected_features: list, best_params: dict) -> str:
    """
    Trains a Challenger using Optuna's optimal parameters on N-40 days, evaluates it blindly 
    against the Champion, and if successful, refits on 100% of the data and promotes it to production.
    
    Args:
        data_path (str): Path to the Parquet dataset generated by the extraction task.
        selected_features (list): List of features to be used for training.
        best_params (dict): Optimal hyperparameters discovered by Optuna.
        
    Returns:
        str: Status message indicating whether the Challenger was promoted or discarded.
    """
    if not os.path.exists(data_path):
        raise FileNotFoundError(f"FATAL: Historical dataset missing at {data_path}")

    df = pd.read_parquet(data_path)
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values('date')

    unique_dates = df['date'].unique()
    cutoff_date = unique_dates[-40]

    train_df = df[df['date'] < cutoff_date].copy()
    test_df = df[df['date'] >= cutoff_date].copy()

    q_high = best_params.pop("q_high")
    q_low = best_params.pop("q_low")
    buy_thresh = best_params.pop("buy_threshold")
    sell_thresh = best_params.pop("sell_threshold")
    
    w_buy = best_params.pop("weight_buy")
    w_sell = best_params.pop("weight_sell")
    w_neutral = best_params.pop("weight_neutral")
    
    lgbm_params = {
        "objective": "multiclass",
        "num_class": 3,
        "metric": "multi_logloss",
        "verbosity": -1,
        "device_type": "cpu",
        "random_state": 1,
        "class_weight": {-1: w_sell, 0: w_neutral, 1: w_buy},
        **best_params
    }

    challenger_target_maker = TargetEngineer(q_high=q_high, q_low=q_low)
    chall_train_df = challenger_target_maker.fit_transform(train_df)
    chall_test_df = challenger_target_maker.transform(test_df)

    X_train_chall = chall_train_df[selected_features]
    y_train_chall = chall_train_df['target']
    X_test_chall = chall_test_df[selected_features]
    y_test_chall = chall_test_df['target']

    print("Training Challenger on N-40 historical data...")
    challenger_model = lgb.LGBMClassifier(**lgbm_params)
    challenger_model.fit(X_train_chall, y_train_chall)

    model_dir = "/opt/airflow/quant_engine/models/etf/production"
    champion_path = os.path.join(model_dir, "etf_baseline_1.joblib")
    config_path = os.path.join(model_dir, "quant_config.json")

    champion_model = joblib.load(champion_path)
    with open(config_path, "r") as f:
        champ_config = json.load(f)

    champ_features = champ_config['req_features']
    champ_buy_thresh = champ_config['buy_threshold']
    champ_sell_thresh = champ_config['sell_threshold']
    
    champ_target_maker = TargetEngineer(q_high=champ_config['q_high_original'], q_low=champ_config['q_low_original'])
    champ_target_maker.thresholds = {'high': champ_config['bull_limit'], 'low': champ_config['bear_limit']}
    
    champ_test_df = test_df.copy()
    champ_test_df['target'] = np.where(
        champ_test_df['fwd_log_return'] >= champ_config['bull_limit'], 1,
        np.where(champ_test_df['fwd_log_return'] <= champ_config['bear_limit'], -1, 0)
    )
    X_test_champ = champ_test_df[champ_features]
    y_test_champ = champ_test_df['target']

    def get_actionable_accuracy(model, X, y_true, u_buy, u_sell):
        probs = model.predict_proba(X)
        idx_sell = np.where(model.classes_ == -1)[0][0]
        idx_buy = np.where(model.classes_ == 1)[0][0]

        actionable_preds = []
        actionable_trues = []

        for i in range(len(probs)):
            if probs[i][idx_buy] >= u_buy:
                actionable_preds.append(1)
                actionable_trues.append(y_true.iloc[i])
            elif probs[i][idx_sell] >= u_sell:
                actionable_preds.append(-1)
                actionable_trues.append(y_true.iloc[i])

        if not actionable_preds:
            return 0.0
        correct = np.sum(np.array(actionable_preds) == np.array(actionable_trues))
        return correct / len(actionable_preds)

    champ_acc = get_actionable_accuracy(champion_model, X_test_champ, y_test_champ, champ_buy_thresh, champ_sell_thresh)
    chall_acc = get_actionable_accuracy(challenger_model, X_test_chall, y_test_chall, buy_thresh, sell_thresh)

    print(f"Blind 40-Day Evaluation - Champion Accuracy: {champ_acc:.2%}")
    print(f"Blind 40-Day Evaluation - Challenger Accuracy: {chall_acc:.2%}")

    tracking_uri = os.getenv("MLFLOW_TRACKING_URI")
        
    mlflow.set_tracking_uri(tracking_uri)
    mlflow.set_experiment("Heavy_Retrain_Validation")

    with mlflow.start_run(run_name=f"Heavy_Optuna_{datetime.now().strftime('%Y-%m-%d')}") as run:
        
        features_summary = df.describe().to_markdown()
        mlflow.log_text(features_summary, "data_health/full_dataset_distribution.md")
        
        mlflow.log_metric("champion_accuracy", champ_acc)
        mlflow.log_metric("challenger_accuracy", chall_acc)
        
        mlflow.log_params(lgbm_params)
        mlflow.log_param("q_high", q_high)
        mlflow.log_param("q_low", q_low)
        mlflow.log_param("buy_threshold", buy_thresh)
        mlflow.log_param("sell_threshold", sell_thresh)

        if chall_acc > champ_acc:
            print("Verdict: OPTUNA CHALLENGER WINS. Refitting on 100% of data...")
            
            final_target_maker = TargetEngineer(q_high=q_high, q_low=q_low)
            final_df = final_target_maker.fit_transform(df)
            
            X_full = final_df[selected_features]
            y_full = final_df['target']
            
            final_model = lgb.LGBMClassifier(**lgbm_params)
            final_model.fit(X_full, y_full)

            exporter = ProductionExporter(export_dir=model_dir)
            exporter.export(
                model=final_model,
                target_engineer=final_target_maker,
                buy_threshold=buy_thresh,
                sell_threshold=sell_thresh,
                lgb_params=lgbm_params,
                train_days=252,
                step_days=20,
                embargo_days=5
            )
            
            mlflow.log_artifact(os.path.join(model_dir, "etf_baseline_1.joblib"))
            mlflow.log_artifact(os.path.join(model_dir, "quant_config.json"))
            mlflow.log_param("promoted", True)
            
            os.remove(data_path)
            return f"HEAVY PROMOTION SUCCESSFUL. Backup stored in MinIO Run ID: {run.info.run_id}"
            
        else:
            print("Verdict: CHAMPION RETAINS THE THRONE. Challenger discarded.")
            mlflow.log_param("promoted", False)
            os.remove(data_path)
            raise AirflowSkipException("Optuna Challenger failed to beat Champion. Production remains unchanged.")
